// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbif.proto

package db

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParameterType int32

const (
	ParameterType_UNKNOWN_TYPE ParameterType = 0
	ParameterType_DOUBLE       ParameterType = 1
	ParameterType_INT          ParameterType = 2
	ParameterType_DISCRETE     ParameterType = 3
	ParameterType_CATEGORICAL  ParameterType = 4
)

var ParameterType_name = map[int32]string{
	0: "UNKNOWN_TYPE",
	1: "DOUBLE",
	2: "INT",
	3: "DISCRETE",
	4: "CATEGORICAL",
}

var ParameterType_value = map[string]int32{
	"UNKNOWN_TYPE": 0,
	"DOUBLE":       1,
	"INT":          2,
	"DISCRETE":     3,
	"CATEGORICAL":  4,
}

func (x ParameterType) String() string {
	return proto.EnumName(ParameterType_name, int32(x))
}

func (ParameterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{0}
}

//*
// Direction of optimization. Minimize or Maximize.
type OptimizationType int32

const (
	OptimizationType_UNKNOWN_OPTIMIZATION OptimizationType = 0
	OptimizationType_MINIMIZE             OptimizationType = 1
	OptimizationType_MAXIMIZE             OptimizationType = 2
)

var OptimizationType_name = map[int32]string{
	0: "UNKNOWN_OPTIMIZATION",
	1: "MINIMIZE",
	2: "MAXIMIZE",
}

var OptimizationType_value = map[string]int32{
	"UNKNOWN_OPTIMIZATION": 0,
	"MINIMIZE":             1,
	"MAXIMIZE":             2,
}

func (x OptimizationType) String() string {
	return proto.EnumName(OptimizationType_name, int32(x))
}

func (OptimizationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{1}
}

type Operation struct {
	OperationType        string                      `protobuf:"bytes,1,opt,name=operationType,proto3" json:"operationType,omitempty"`
	ParameterConfigs     *Operation_ParameterConfigs `protobuf:"bytes,2,opt,name=parameter_configs,json=parameterConfigs,proto3" json:"parameter_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{0}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *Operation) GetParameterConfigs() *Operation_ParameterConfigs {
	if m != nil {
		return m.ParameterConfigs
	}
	return nil
}

//*
// List of ParameterConfig
type Operation_ParameterConfigs struct {
	Configs              []*ParameterConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Operation_ParameterConfigs) Reset()         { *m = Operation_ParameterConfigs{} }
func (m *Operation_ParameterConfigs) String() string { return proto.CompactTextString(m) }
func (*Operation_ParameterConfigs) ProtoMessage()    {}
func (*Operation_ParameterConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{0, 0}
}

func (m *Operation_ParameterConfigs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation_ParameterConfigs.Unmarshal(m, b)
}
func (m *Operation_ParameterConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation_ParameterConfigs.Marshal(b, m, deterministic)
}
func (m *Operation_ParameterConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation_ParameterConfigs.Merge(m, src)
}
func (m *Operation_ParameterConfigs) XXX_Size() int {
	return xxx_messageInfo_Operation_ParameterConfigs.Size(m)
}
func (m *Operation_ParameterConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation_ParameterConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_Operation_ParameterConfigs proto.InternalMessageInfo

func (m *Operation_ParameterConfigs) GetConfigs() []*ParameterConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

type NasConfig struct {
	GraphConfig          *GraphConfig          `protobuf:"bytes,1,opt,name=graph_config,json=graphConfig,proto3" json:"graph_config,omitempty"`
	Operations           *NasConfig_Operations `protobuf:"bytes,2,opt,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NasConfig) Reset()         { *m = NasConfig{} }
func (m *NasConfig) String() string { return proto.CompactTextString(m) }
func (*NasConfig) ProtoMessage()    {}
func (*NasConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{1}
}

func (m *NasConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NasConfig.Unmarshal(m, b)
}
func (m *NasConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NasConfig.Marshal(b, m, deterministic)
}
func (m *NasConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NasConfig.Merge(m, src)
}
func (m *NasConfig) XXX_Size() int {
	return xxx_messageInfo_NasConfig.Size(m)
}
func (m *NasConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NasConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NasConfig proto.InternalMessageInfo

func (m *NasConfig) GetGraphConfig() *GraphConfig {
	if m != nil {
		return m.GraphConfig
	}
	return nil
}

func (m *NasConfig) GetOperations() *NasConfig_Operations {
	if m != nil {
		return m.Operations
	}
	return nil
}

type NasConfig_Operations struct {
	Operation            []*Operation `protobuf:"bytes,1,rep,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NasConfig_Operations) Reset()         { *m = NasConfig_Operations{} }
func (m *NasConfig_Operations) String() string { return proto.CompactTextString(m) }
func (*NasConfig_Operations) ProtoMessage()    {}
func (*NasConfig_Operations) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{1, 0}
}

func (m *NasConfig_Operations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NasConfig_Operations.Unmarshal(m, b)
}
func (m *NasConfig_Operations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NasConfig_Operations.Marshal(b, m, deterministic)
}
func (m *NasConfig_Operations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NasConfig_Operations.Merge(m, src)
}
func (m *NasConfig_Operations) XXX_Size() int {
	return xxx_messageInfo_NasConfig_Operations.Size(m)
}
func (m *NasConfig_Operations) XXX_DiscardUnknown() {
	xxx_messageInfo_NasConfig_Operations.DiscardUnknown(m)
}

var xxx_messageInfo_NasConfig_Operations proto.InternalMessageInfo

func (m *NasConfig_Operations) GetOperation() []*Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type GraphConfig struct {
	NumLayers            int32    `protobuf:"varint,1,opt,name=num_layers,json=numLayers,proto3" json:"num_layers,omitempty"`
	InputSize            []int32  `protobuf:"varint,2,rep,packed,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	OutputSize           []int32  `protobuf:"varint,3,rep,packed,name=output_size,json=outputSize,proto3" json:"output_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphConfig) Reset()         { *m = GraphConfig{} }
func (m *GraphConfig) String() string { return proto.CompactTextString(m) }
func (*GraphConfig) ProtoMessage()    {}
func (*GraphConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{2}
}

func (m *GraphConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphConfig.Unmarshal(m, b)
}
func (m *GraphConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphConfig.Marshal(b, m, deterministic)
}
func (m *GraphConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphConfig.Merge(m, src)
}
func (m *GraphConfig) XXX_Size() int {
	return xxx_messageInfo_GraphConfig.Size(m)
}
func (m *GraphConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GraphConfig proto.InternalMessageInfo

func (m *GraphConfig) GetNumLayers() int32 {
	if m != nil {
		return m.NumLayers
	}
	return 0
}

func (m *GraphConfig) GetInputSize() []int32 {
	if m != nil {
		return m.InputSize
	}
	return nil
}

func (m *GraphConfig) GetOutputSize() []int32 {
	if m != nil {
		return m.OutputSize
	}
	return nil
}

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{3}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{4}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ParameterConfig struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParameterType        ParameterType  `protobuf:"varint,2,opt,name=parameter_type,json=parameterType,proto3,enum=db.ParameterType" json:"parameter_type,omitempty"`
	Feasible             *FeasibleSpace `protobuf:"bytes,3,opt,name=feasible,proto3" json:"feasible,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ParameterConfig) Reset()         { *m = ParameterConfig{} }
func (m *ParameterConfig) String() string { return proto.CompactTextString(m) }
func (*ParameterConfig) ProtoMessage()    {}
func (*ParameterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{5}
}

func (m *ParameterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParameterConfig.Unmarshal(m, b)
}
func (m *ParameterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParameterConfig.Marshal(b, m, deterministic)
}
func (m *ParameterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterConfig.Merge(m, src)
}
func (m *ParameterConfig) XXX_Size() int {
	return xxx_messageInfo_ParameterConfig.Size(m)
}
func (m *ParameterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterConfig proto.InternalMessageInfo

func (m *ParameterConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParameterConfig) GetParameterType() ParameterType {
	if m != nil {
		return m.ParameterType
	}
	return ParameterType_UNKNOWN_TYPE
}

func (m *ParameterConfig) GetFeasible() *FeasibleSpace {
	if m != nil {
		return m.Feasible
	}
	return nil
}

type Tag struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{6}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FeasibleSpace struct {
	Max                  string   `protobuf:"bytes,1,opt,name=max,proto3" json:"max,omitempty"`
	Min                  string   `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	List                 []string `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	Step                 string   `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeasibleSpace) Reset()         { *m = FeasibleSpace{} }
func (m *FeasibleSpace) String() string { return proto.CompactTextString(m) }
func (*FeasibleSpace) ProtoMessage()    {}
func (*FeasibleSpace) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{7}
}

func (m *FeasibleSpace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeasibleSpace.Unmarshal(m, b)
}
func (m *FeasibleSpace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeasibleSpace.Marshal(b, m, deterministic)
}
func (m *FeasibleSpace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeasibleSpace.Merge(m, src)
}
func (m *FeasibleSpace) XXX_Size() int {
	return xxx_messageInfo_FeasibleSpace.Size(m)
}
func (m *FeasibleSpace) XXX_DiscardUnknown() {
	xxx_messageInfo_FeasibleSpace.DiscardUnknown(m)
}

var xxx_messageInfo_FeasibleSpace proto.InternalMessageInfo

func (m *FeasibleSpace) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *FeasibleSpace) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *FeasibleSpace) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *FeasibleSpace) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

type StudyConfig struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string                        `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	OptimizationType     OptimizationType              `protobuf:"varint,3,opt,name=optimization_type,json=optimizationType,proto3,enum=db.OptimizationType" json:"optimization_type,omitempty"`
	OptimizationGoal     float64                       `protobuf:"fixed64,4,opt,name=optimization_goal,json=optimizationGoal,proto3" json:"optimization_goal,omitempty"`
	ParameterConfigs     *StudyConfig_ParameterConfigs `protobuf:"bytes,5,opt,name=parameter_configs,json=parameterConfigs,proto3" json:"parameter_configs,omitempty"`
	AccessPermissions    []string                      `protobuf:"bytes,6,rep,name=access_permissions,json=accessPermissions,proto3" json:"access_permissions,omitempty"`
	Tags                 []*Tag                        `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	ObjectiveValueName   string                        `protobuf:"bytes,8,opt,name=objective_value_name,json=objectiveValueName,proto3" json:"objective_value_name,omitempty"`
	Metrics              []string                      `protobuf:"bytes,9,rep,name=metrics,proto3" json:"metrics,omitempty"`
	JobId                string                        `protobuf:"bytes,10,opt,name=jobId,proto3" json:"jobId,omitempty"`
	NasConfig            *NasConfig                    `protobuf:"bytes,11,opt,name=nas_config,json=nasConfig,proto3" json:"nas_config,omitempty"`
	JobType              string                        `protobuf:"bytes,12,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *StudyConfig) Reset()         { *m = StudyConfig{} }
func (m *StudyConfig) String() string { return proto.CompactTextString(m) }
func (*StudyConfig) ProtoMessage()    {}
func (*StudyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{8}
}

func (m *StudyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudyConfig.Unmarshal(m, b)
}
func (m *StudyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudyConfig.Marshal(b, m, deterministic)
}
func (m *StudyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudyConfig.Merge(m, src)
}
func (m *StudyConfig) XXX_Size() int {
	return xxx_messageInfo_StudyConfig.Size(m)
}
func (m *StudyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StudyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StudyConfig proto.InternalMessageInfo

func (m *StudyConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudyConfig) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *StudyConfig) GetOptimizationType() OptimizationType {
	if m != nil {
		return m.OptimizationType
	}
	return OptimizationType_UNKNOWN_OPTIMIZATION
}

func (m *StudyConfig) GetOptimizationGoal() float64 {
	if m != nil {
		return m.OptimizationGoal
	}
	return 0
}

func (m *StudyConfig) GetParameterConfigs() *StudyConfig_ParameterConfigs {
	if m != nil {
		return m.ParameterConfigs
	}
	return nil
}

func (m *StudyConfig) GetAccessPermissions() []string {
	if m != nil {
		return m.AccessPermissions
	}
	return nil
}

func (m *StudyConfig) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StudyConfig) GetObjectiveValueName() string {
	if m != nil {
		return m.ObjectiveValueName
	}
	return ""
}

func (m *StudyConfig) GetMetrics() []string {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *StudyConfig) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *StudyConfig) GetNasConfig() *NasConfig {
	if m != nil {
		return m.NasConfig
	}
	return nil
}

func (m *StudyConfig) GetJobType() string {
	if m != nil {
		return m.JobType
	}
	return ""
}

//*
// List of ParameterConfig
type StudyConfig_ParameterConfigs struct {
	Configs              []*ParameterConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StudyConfig_ParameterConfigs) Reset()         { *m = StudyConfig_ParameterConfigs{} }
func (m *StudyConfig_ParameterConfigs) String() string { return proto.CompactTextString(m) }
func (*StudyConfig_ParameterConfigs) ProtoMessage()    {}
func (*StudyConfig_ParameterConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{8, 0}
}

func (m *StudyConfig_ParameterConfigs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudyConfig_ParameterConfigs.Unmarshal(m, b)
}
func (m *StudyConfig_ParameterConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudyConfig_ParameterConfigs.Marshal(b, m, deterministic)
}
func (m *StudyConfig_ParameterConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudyConfig_ParameterConfigs.Merge(m, src)
}
func (m *StudyConfig_ParameterConfigs) XXX_Size() int {
	return xxx_messageInfo_StudyConfig_ParameterConfigs.Size(m)
}
func (m *StudyConfig_ParameterConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_StudyConfig_ParameterConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_StudyConfig_ParameterConfigs proto.InternalMessageInfo

func (m *StudyConfig_ParameterConfigs) GetConfigs() []*ParameterConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

type CreateStudyRequest struct {
	StudyConfig          *StudyConfig `protobuf:"bytes,1,opt,name=study_config,json=studyConfig,proto3" json:"study_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateStudyRequest) Reset()         { *m = CreateStudyRequest{} }
func (m *CreateStudyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStudyRequest) ProtoMessage()    {}
func (*CreateStudyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{9}
}

func (m *CreateStudyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudyRequest.Unmarshal(m, b)
}
func (m *CreateStudyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudyRequest.Marshal(b, m, deterministic)
}
func (m *CreateStudyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudyRequest.Merge(m, src)
}
func (m *CreateStudyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStudyRequest.Size(m)
}
func (m *CreateStudyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudyRequest proto.InternalMessageInfo

func (m *CreateStudyRequest) GetStudyConfig() *StudyConfig {
	if m != nil {
		return m.StudyConfig
	}
	return nil
}

//*
// Return generated StudyID.
type CreateStudyReply struct {
	StudyId              string   `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudyReply) Reset()         { *m = CreateStudyReply{} }
func (m *CreateStudyReply) String() string { return proto.CompactTextString(m) }
func (*CreateStudyReply) ProtoMessage()    {}
func (*CreateStudyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{10}
}

func (m *CreateStudyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudyReply.Unmarshal(m, b)
}
func (m *CreateStudyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudyReply.Marshal(b, m, deterministic)
}
func (m *CreateStudyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudyReply.Merge(m, src)
}
func (m *CreateStudyReply) XXX_Size() int {
	return xxx_messageInfo_CreateStudyReply.Size(m)
}
func (m *CreateStudyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudyReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudyReply proto.InternalMessageInfo

func (m *CreateStudyReply) GetStudyId() string {
	if m != nil {
		return m.StudyId
	}
	return ""
}

type GetStudyRequest struct {
	StudyId              string   `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudyRequest) Reset()         { *m = GetStudyRequest{} }
func (m *GetStudyRequest) String() string { return proto.CompactTextString(m) }
func (*GetStudyRequest) ProtoMessage()    {}
func (*GetStudyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{11}
}

func (m *GetStudyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudyRequest.Unmarshal(m, b)
}
func (m *GetStudyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudyRequest.Marshal(b, m, deterministic)
}
func (m *GetStudyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudyRequest.Merge(m, src)
}
func (m *GetStudyRequest) XXX_Size() int {
	return xxx_messageInfo_GetStudyRequest.Size(m)
}
func (m *GetStudyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudyRequest proto.InternalMessageInfo

func (m *GetStudyRequest) GetStudyId() string {
	if m != nil {
		return m.StudyId
	}
	return ""
}

//*
// Return a config of specified Study.
type GetStudyReply struct {
	StudyConfig          *StudyConfig `protobuf:"bytes,1,opt,name=study_config,json=studyConfig,proto3" json:"study_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetStudyReply) Reset()         { *m = GetStudyReply{} }
func (m *GetStudyReply) String() string { return proto.CompactTextString(m) }
func (*GetStudyReply) ProtoMessage()    {}
func (*GetStudyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a2d42ab756d553, []int{12}
}

func (m *GetStudyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudyReply.Unmarshal(m, b)
}
func (m *GetStudyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudyReply.Marshal(b, m, deterministic)
}
func (m *GetStudyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudyReply.Merge(m, src)
}
func (m *GetStudyReply) XXX_Size() int {
	return xxx_messageInfo_GetStudyReply.Size(m)
}
func (m *GetStudyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudyReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudyReply proto.InternalMessageInfo

func (m *GetStudyReply) GetStudyConfig() *StudyConfig {
	if m != nil {
		return m.StudyConfig
	}
	return nil
}

func init() {
	proto.RegisterEnum("db.ParameterType", ParameterType_name, ParameterType_value)
	proto.RegisterEnum("db.OptimizationType", OptimizationType_name, OptimizationType_value)
	proto.RegisterType((*Operation)(nil), "db.Operation")
	proto.RegisterType((*Operation_ParameterConfigs)(nil), "db.Operation.ParameterConfigs")
	proto.RegisterType((*NasConfig)(nil), "db.NasConfig")
	proto.RegisterType((*NasConfig_Operations)(nil), "db.NasConfig.Operations")
	proto.RegisterType((*GraphConfig)(nil), "db.GraphConfig")
	proto.RegisterType((*HelloRequest)(nil), "db.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "db.HelloReply")
	proto.RegisterType((*ParameterConfig)(nil), "db.ParameterConfig")
	proto.RegisterType((*Tag)(nil), "db.Tag")
	proto.RegisterType((*FeasibleSpace)(nil), "db.FeasibleSpace")
	proto.RegisterType((*StudyConfig)(nil), "db.StudyConfig")
	proto.RegisterType((*StudyConfig_ParameterConfigs)(nil), "db.StudyConfig.ParameterConfigs")
	proto.RegisterType((*CreateStudyRequest)(nil), "db.CreateStudyRequest")
	proto.RegisterType((*CreateStudyReply)(nil), "db.CreateStudyReply")
	proto.RegisterType((*GetStudyRequest)(nil), "db.GetStudyRequest")
	proto.RegisterType((*GetStudyReply)(nil), "db.GetStudyReply")
}

func init() { proto.RegisterFile("dbif.proto", fileDescriptor_23a2d42ab756d553) }

var fileDescriptor_23a2d42ab756d553 = []byte{
	// 892 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xe2, 0x56,
	0x10, 0x8e, 0x81, 0x04, 0x3c, 0x86, 0xc4, 0x4c, 0x51, 0xe5, 0xa5, 0x6a, 0x8b, 0xac, 0xaa, 0x8a,
	0x76, 0x37, 0xb4, 0xa2, 0xbd, 0xd8, 0x5e, 0xf4, 0x82, 0x25, 0x6c, 0x62, 0x6d, 0x02, 0x91, 0x71,
	0xfa, 0x7b, 0x81, 0x8e, 0xe1, 0x84, 0x3a, 0x32, 0xb6, 0xeb, 0x63, 0xb6, 0x25, 0x0f, 0xd1, 0x17,
	0xe9, 0x4d, 0x2f, 0xfa, 0x02, 0x7d, 0xb3, 0xea, 0x8c, 0x31, 0xc6, 0x6c, 0xb4, 0xaa, 0xaa, 0xbd,
	0xf3, 0x7c, 0x33, 0xe7, 0x3b, 0x33, 0xdf, 0xcc, 0x1c, 0x03, 0xcc, 0x5d, 0xef, 0xae, 0x1b, 0xc5,
	0x61, 0x12, 0x62, 0x69, 0xee, 0x9a, 0xff, 0x28, 0xa0, 0x8e, 0x23, 0x1e, 0xb3, 0xc4, 0x0b, 0x03,
	0xfc, 0x0c, 0x1a, 0x61, 0x66, 0x38, 0xeb, 0x88, 0x1b, 0x4a, 0x47, 0x39, 0x55, 0xed, 0x22, 0x88,
	0xaf, 0xa1, 0x19, 0xb1, 0x98, 0x2d, 0x79, 0xc2, 0xe3, 0xe9, 0x2c, 0x0c, 0xee, 0xbc, 0x85, 0x30,
	0x4a, 0x1d, 0xe5, 0x54, 0xeb, 0x7d, 0xd2, 0x9d, 0xbb, 0xdd, 0x2d, 0x5f, 0xf7, 0x26, 0x0b, 0x1b,
	0xa4, 0x51, 0xb6, 0x1e, 0xed, 0x21, 0xed, 0x3e, 0xe8, 0xfb, 0x51, 0x78, 0x06, 0xd5, 0x8c, 0x56,
	0xe9, 0x94, 0x4f, 0xb5, 0xde, 0x07, 0x92, 0x76, 0x2f, 0xcc, 0xce, 0x62, 0xcc, 0xbf, 0x15, 0x50,
	0x47, 0x4c, 0xa4, 0x30, 0xf6, 0xa0, 0xbe, 0x88, 0x59, 0xf4, 0xcb, 0x26, 0x33, 0x2a, 0x41, 0xeb,
	0x9d, 0x48, 0x86, 0x0b, 0x89, 0x6f, 0x4e, 0x6b, 0x8b, 0xdc, 0xc0, 0x17, 0x00, 0xdb, 0x12, 0xb3,
	0x52, 0x0c, 0x79, 0x62, 0x4b, 0x9b, 0x17, 0x25, 0xec, 0x9d, 0xd8, 0xf6, 0x37, 0x00, 0xb9, 0x07,
	0x9f, 0x81, 0xba, 0xf5, 0x6d, 0x52, 0x6f, 0x14, 0x14, 0xb1, 0x73, 0xbf, 0xe9, 0x83, 0xb6, 0x93,
	0x10, 0x7e, 0x0c, 0x10, 0xac, 0x96, 0x53, 0x9f, 0xad, 0x79, 0x2c, 0x28, 0xeb, 0x43, 0x5b, 0x0d,
	0x56, 0xcb, 0x2b, 0x02, 0xa4, 0xdb, 0x0b, 0xa2, 0x55, 0x32, 0x15, 0xde, 0x03, 0x37, 0x4a, 0x9d,
	0xb2, 0x74, 0x13, 0x32, 0xf1, 0x1e, 0x38, 0x7e, 0x0a, 0x5a, 0xb8, 0x4a, 0xb6, 0xfe, 0x32, 0xf9,
	0x21, 0x85, 0x64, 0x80, 0x69, 0x42, 0xfd, 0x92, 0xfb, 0x7e, 0x68, 0xf3, 0x5f, 0x57, 0x5c, 0x24,
	0x88, 0x50, 0x09, 0xd8, 0x32, 0xeb, 0x30, 0x7d, 0x9b, 0x9f, 0x03, 0x6c, 0x62, 0x22, 0x7f, 0x8d,
	0x06, 0x54, 0x97, 0x5c, 0x08, 0xb6, 0xc8, 0x82, 0x32, 0xd3, 0xfc, 0x43, 0x81, 0x93, 0xbd, 0x6e,
	0x3c, 0xc6, 0x87, 0x2f, 0xe0, 0x38, 0x1f, 0x94, 0x44, 0xce, 0x93, 0x94, 0xf6, 0xb8, 0xd7, 0x2c,
	0xb4, 0x53, 0xce, 0x94, 0xdd, 0x88, 0x76, 0x4d, 0x3c, 0x83, 0xda, 0x1d, 0x67, 0xc2, 0x73, 0x7d,
	0x59, 0x8b, 0x6c, 0x07, 0x9d, 0x79, 0xb5, 0xc1, 0x26, 0x11, 0x9b, 0x71, 0x7b, 0x1b, 0x62, 0x7e,
	0x01, 0x65, 0x87, 0x3d, 0x9e, 0x43, 0x0b, 0x0e, 0xdf, 0x30, 0x7f, 0x95, 0x5e, 0xad, 0xda, 0xa9,
	0x61, 0xfe, 0x0c, 0x8d, 0x02, 0x17, 0xea, 0x50, 0x5e, 0xb2, 0xdf, 0x37, 0x27, 0xe5, 0x27, 0x21,
	0x5e, 0xb0, 0x39, 0x26, 0x3f, 0x25, 0xbd, 0xef, 0x89, 0x84, 0xc4, 0x55, 0x6d, 0xfa, 0x96, 0x98,
	0x48, 0x78, 0x64, 0x54, 0xd2, 0x2b, 0xe5, 0xb7, 0xf9, 0x57, 0x05, 0xb4, 0x49, 0xb2, 0x9a, 0xaf,
	0xdf, 0x21, 0x4d, 0x0b, 0x0e, 0xc3, 0xdf, 0x02, 0x1e, 0x67, 0x69, 0x91, 0x81, 0x7d, 0x68, 0x86,
	0x51, 0xe2, 0x2d, 0xbd, 0x07, 0x1a, 0x91, 0x54, 0xb3, 0x32, 0x69, 0xd6, 0x4a, 0xe7, 0x28, 0x77,
	0x92, 0x6c, 0x7a, 0xb8, 0x87, 0xe0, 0xb3, 0x3d, 0x8a, 0x45, 0xc8, 0x7c, 0xca, 0x4e, 0x29, 0x06,
	0x5f, 0x84, 0xcc, 0xc7, 0xeb, 0xc7, 0x36, 0xf9, 0x90, 0xf4, 0xee, 0xc8, 0xfb, 0x76, 0xaa, 0xf8,
	0x0f, 0xbb, 0x8c, 0x67, 0x80, 0x6c, 0x36, 0xe3, 0x42, 0x4c, 0x23, 0x1e, 0x2f, 0x3d, 0x21, 0x68,
	0x9d, 0x8e, 0x48, 0xae, 0x66, 0xea, 0xb9, 0xc9, 0x1d, 0xf8, 0x11, 0x54, 0x12, 0xb6, 0x10, 0x46,
	0x95, 0x16, 0xa5, 0x2a, 0x2f, 0x74, 0xd8, 0xc2, 0x26, 0x10, 0xbf, 0x84, 0x56, 0xe8, 0xde, 0xf3,
	0x59, 0xe2, 0xbd, 0xe1, 0x53, 0x6a, 0xda, 0x94, 0x44, 0xac, 0x91, 0x5e, 0xb8, 0xf5, 0x7d, 0x27,
	0x5d, 0x23, 0x29, 0x29, 0xcd, 0x6b, 0x12, 0x7b, 0x33, 0x61, 0xa8, 0x74, 0x65, 0x66, 0x4a, 0xb1,
	0xef, 0x43, 0xd7, 0x9a, 0x1b, 0x90, 0x8a, 0x4d, 0x06, 0x3e, 0x07, 0x08, 0x98, 0xc8, 0x9e, 0x09,
	0x8d, 0xaa, 0x6e, 0x14, 0x96, 0xde, 0x56, 0x83, 0xed, 0xb3, 0xf2, 0x04, 0x6a, 0xf7, 0xa1, 0x9b,
	0x76, 0xa4, 0x9e, 0xae, 0xc3, 0x7d, 0xe8, 0x4a, 0xc9, 0xdf, 0xc7, 0x13, 0x76, 0x09, 0x38, 0x88,
	0x39, 0x4b, 0x38, 0x29, 0x9e, 0xed, 0x68, 0x0f, 0xea, 0x42, 0xda, 0x8f, 0x3c, 0x65, 0x3b, 0x9d,
	0xb1, 0x35, 0x91, 0x1b, 0xe6, 0x19, 0xe8, 0x05, 0x26, 0xb9, 0xc9, 0x4f, 0xa0, 0x96, 0xf2, 0x78,
	0xf3, 0x6c, 0x95, 0xc9, 0xb6, 0xe6, 0xe6, 0x73, 0x38, 0xb9, 0xe0, 0x49, 0xe1, 0xd6, 0x77, 0x44,
	0x0f, 0xa0, 0x91, 0x47, 0x4b, 0xe6, 0xff, 0x91, 0xe1, 0xd3, 0x5b, 0x68, 0x14, 0x76, 0x1f, 0x75,
	0xa8, 0xdf, 0x8e, 0x5e, 0x8f, 0xc6, 0xdf, 0x8f, 0xa6, 0xce, 0x8f, 0x37, 0x43, 0xfd, 0x00, 0x01,
	0x8e, 0xce, 0xc7, 0xb7, 0x2f, 0xaf, 0x86, 0xba, 0x82, 0x55, 0x28, 0x5b, 0x23, 0x47, 0x2f, 0x61,
	0x1d, 0x6a, 0xe7, 0xd6, 0x64, 0x60, 0x0f, 0x9d, 0xa1, 0x5e, 0xc6, 0x13, 0xd0, 0x06, 0x7d, 0x67,
	0x78, 0x31, 0xb6, 0xad, 0x41, 0xff, 0x4a, 0xaf, 0x3c, 0xbd, 0x04, 0x7d, 0x7f, 0x3d, 0xd0, 0x80,
	0x56, 0xc6, 0x3c, 0xbe, 0x71, 0xac, 0x6b, 0xeb, 0xa7, 0xbe, 0x63, 0x8d, 0x47, 0xfa, 0x81, 0x24,
	0xbb, 0xb6, 0x46, 0x12, 0x91, 0x77, 0x48, 0xab, 0xff, 0x43, 0x6a, 0x95, 0x7a, 0x7f, 0x2a, 0x50,
	0x39, 0x7f, 0x69, 0xbd, 0xc2, 0x2e, 0xd4, 0x26, 0x6c, 0x4d, 0x4f, 0x22, 0xea, 0xb2, 0xa6, 0xdd,
	0x17, 0xb4, 0x7d, 0xbc, 0x83, 0x44, 0xfe, 0xda, 0x3c, 0xc0, 0x6f, 0x41, 0xdb, 0xd1, 0x1e, 0x3f,
	0x94, 0x01, 0x6f, 0xb7, 0xb5, 0xdd, 0x7a, 0x0b, 0x4f, 0x8f, 0x7f, 0x0d, 0xb5, 0x4c, 0x5d, 0xa4,
	0x71, 0xd9, 0xeb, 0x4c, 0xbb, 0x59, 0x04, 0xe9, 0x94, 0x7b, 0x44, 0x3f, 0xf3, 0xaf, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x3d, 0x11, 0x3a, 0x8a, 0xda, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBIFClient is the client API for DBIF service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBIFClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	CreateStudy(ctx context.Context, in *CreateStudyRequest, opts ...grpc.CallOption) (*CreateStudyReply, error)
	GetStudy(ctx context.Context, in *GetStudyRequest, opts ...grpc.CallOption) (*GetStudyReply, error)
}

type dBIFClient struct {
	cc *grpc.ClientConn
}

func NewDBIFClient(cc *grpc.ClientConn) DBIFClient {
	return &dBIFClient{cc}
}

func (c *dBIFClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/db.DBIF/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBIFClient) CreateStudy(ctx context.Context, in *CreateStudyRequest, opts ...grpc.CallOption) (*CreateStudyReply, error) {
	out := new(CreateStudyReply)
	err := c.cc.Invoke(ctx, "/db.DBIF/CreateStudy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBIFClient) GetStudy(ctx context.Context, in *GetStudyRequest, opts ...grpc.CallOption) (*GetStudyReply, error) {
	out := new(GetStudyReply)
	err := c.cc.Invoke(ctx, "/db.DBIF/GetStudy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBIFServer is the server API for DBIF service.
type DBIFServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	CreateStudy(context.Context, *CreateStudyRequest) (*CreateStudyReply, error)
	GetStudy(context.Context, *GetStudyRequest) (*GetStudyReply, error)
}

func RegisterDBIFServer(s *grpc.Server, srv DBIFServer) {
	s.RegisterService(&_DBIF_serviceDesc, srv)
}

func _DBIF_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBIFServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DBIF/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBIFServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBIF_CreateStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBIFServer).CreateStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DBIF/CreateStudy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBIFServer).CreateStudy(ctx, req.(*CreateStudyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBIF_GetStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBIFServer).GetStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DBIF/GetStudy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBIFServer).GetStudy(ctx, req.(*GetStudyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DBIF_serviceDesc = grpc.ServiceDesc{
	ServiceName: "db.DBIF",
	HandlerType: (*DBIFServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _DBIF_SayHello_Handler,
		},
		{
			MethodName: "CreateStudy",
			Handler:    _DBIF_CreateStudy_Handler,
		},
		{
			MethodName: "GetStudy",
			Handler:    _DBIF_GetStudy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbif.proto",
}
