apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-db-backend
  namespace: kubeflow
  labels:
    app: katib
    component: mysql-db-backend
spec:
  replicas: 1
  template:
    metadata:
      name: mysql-db-backend
      labels:
        app: katib
        component: mysql-db-backend
    spec:
      containers:
      - name: mysql-db-backend
        image: katib/dbif-mysql
        ports:
        - name: api
          containerPort: 6789
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
