apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dbif-mysql
  namespace: kubeflow
  labels:
    app: vizier
    component: dbif-mysql
spec:
  replicas: 1
  template:
    metadata:
      name: dbif-mysql
      labels:
        app: vizier
        component: dbif-mysql
    spec:
      containers:
      - name: dbif-mysql
        image: katib/dbif-mysql
        ports:
        - name: api
          containerPort: 6789
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
