apiVersion: v1
kind: Service
metadata:
  name: dbif-mysql
  namespace: kubeflow
  labels:
    app: vizier
    component: dbif-mysql
spec:
  type: ClusterIP
  ports:
    - port: 6789
      protocol: TCP
      name: api
  selector:
    app: vizier
    component: dbif-mysql
