apiVersion: v1
kind: Service
metadata:
  name: mysql-db-backend
  namespace: kubeflow
  labels:
    app: vizier
    component: mysql-db-backend
spec:
  type: ClusterIP
  ports:
    - port: 6789
      protocol: TCP
      name: api
  selector:
    app: vizier
    component: mysql-db-backend
